title: O. Erencan Dural
logo: /assets/img/erencan.jpg
description: Under construction! Hello, I'm Erencan. I like robots, hearts and magic. ðŸ¤–ðŸ’–âœ¨

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

# Navigation menu
navigation:
  - title: "Home"
    url: /
  - title: "Blog"
    url: /blog
  - title: "Portfolio"
    url: /portfolio
  - title: "Resume"
    url: /resume
