title: O. Erencan Dural
logo: /assets/img/erencan.jpg
description: Under construction! Hello, I'm Erencan. I like robots, hearts and magic. ğŸ¤–ğŸ’–ğŸ”®

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
